#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  15 00:13:18 2022
@author: alivaliyev
"""


#In this lab assignment, your task is to define three functions to process a list.

#You should define the list variable and initiate it with the following:

#[15, 3, 1, None, 9, 20, None, 25, 56, 14, 90, None, 0, 80, 96, 36, None]
#Functions that you are required to define are listed below: 

#CountNoneValues(): This function should return the number of None variables in the list. The function should accept the list as a parameter.
#SumOfNumbers(): This function should return the total of the numbers in a given list. The function should accept the list as a parameter.
#CountIfBigger(): This function should return the number of numbers bigger than the given threshold. For example, assuming that myList is [1,2,3,4,5], CountIfBigger(3, myList) shoult return 2 since there are only two numbers bigger than 3 in the list (which are 4, and 5).
#CompareOddEvenNumbers(): This function should print if the the number of odd values or the number of even values are higher in a list. For example, assuming that myList is [1,2,3,4,5], the function should print "There are more odd numbers than even numbers."; assuming that myList is [2,4,6,1,3], the function should print "There are more even numbers than odd numbers."


def CountNoneValues(arr):
  k=0
  for i in arr:
    if i==None:
      k=k+1
  return k
def SumOfNumbers(arr):
  sum=0
  for i in arr:
    if i!=None:
      sum=sum+i
  return sum
def CountIfBigger(threshold, arr):
  k=0
  for i in arr:
    if i!=None:
      if i>threshold:
        k=k+1
  return k
def CompareOddEvenNumbers(arr):
  num_of_odds=0
  num_of_evens=0
  for i in arr:
    if i!=None:
      if i%2==0:
        num_of_evens=num_of_evens+1
      elif i%2==1:
        num_of_odds=num_of_odds+1
  if num_of_odds>num_of_evens:
    return "There are more odd numbers than even numbers."
  elif num_of_odds<num_of_evens:
    return "There are more even numbers than odd numbers."
  else:
    return "The number of even numbers is equal to the number of odd numbers."
